import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Navbar from "@/Component/Navbar";
import FloatingCTAButton from "@/Component/Floatingctabutton"
import WhatsAppCTAButton from "@/Component/Whatsappctabutton"
const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html
      lang="en"
      className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
    >
      <body className="min-h-full flex flex-col">
        <Navbar />

        <WhatsAppCTAButton className="mb-15"
          phoneNumber="9106550601"
          message="Hi! I'd like to know more about your products."
          tooltipText="Hi! How can we help you? 👋"
          showTooltip={true}
        />

        <FloatingCTAButton
          href="#distribution"
          text="Become Distributor"
        />
        {children}
      </body>
    </html>
  );
}
